projet_westaflex_platform:
    resource: "@ProjetWestaflexPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path: /login
    defaults:

        _controller: UserUserBundle:Security:login


login_check:
    path: /login_check


logout:
    path: /logout
