<?php

namespace ProjetWestaflex\PlatformBundle\Repository;

/**
 * Config_tubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Config_tubeRepository extends \Doctrine\ORM\EntityRepository
{
}
