<?php

namespace ProjetWestaflex\PlatformBundle\Repository;

/**
 * SelectionProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectionProcedureRepository extends \Doctrine\ORM\EntityRepository
{
}
